// Providers
export const DB_CONNECTION = 'DATABASE_CONNECTION';

export const USER_REPOSITORY = 'USER_REPOSITORY';
export const USER_TYPE_REPOSITORY = 'USER_TYPE_REPOSITORY';

export const CONNECTION_REPOSITORY = 'CONNECTION_REPOSITORY';
export const CONNECTION_TYPE_REPOSITORY = 'CONNECTION_TYPE_REPOSITORY';

export const MODEL_REPOSITORY = 'MODEL_REPOSITORY';
export const MODEL_ITEM_REPOSITORY = 'MODEL_ITEM_REPOSITORY';
export const MODEL_ITEM_FIELD_REPOSITORY = 'MODEL_ITEM_FIELD_REPOSITORY';
export const MODEL_ITEM_RELATION_REPOSITORY = 'MODEL_ITEM_RELATION_REPOSITORY';

export const DASHBOARD_REPOSITORY = 'DASHBOARD_REPOSITORY';

export const REPORT_REPOSITORY = 'REPORT_REPOSITORY';
export const REPORT_TYPE_REPOSITORY = 'REPORT_TYPE_REPOSITORY';
export const REPORT_ITEM_REPOSITORY = 'REPORT_ITEM_REPOSITORY';
